package boundedrun

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"time"
)

// FileGoal is a measurable goal of this native adapter. It is intentionally
// explicit about its supported job: reconcile up to three text files. Other
// runtimes can use the same gated tools, but cannot claim this capability just
// by reporting a runtime label.
type FileGoal struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}
type FileTask struct {
	Kind  string     `json:"kind"`
	Files []FileGoal `json:"files"`
}
type FileEvidence struct {
	Path         string    `json:"path"`
	ExpectedHash string    `json:"expected_hash"`
	ObservedHash string    `json:"observed_hash"`
	Verified     bool      `json:"verified"`
	ObservedAt   time.Time `json:"observed_at"`
}
type Outcome struct {
	// Submitted means the execution's measurements are ready for human review.
	// It cannot accept an OKR or mark a KR completed on the human's behalf.
	Status      string         `json:"status"`
	Reason      string         `json:"reason,omitempty"`
	BlockedPath string         `json:"blocked_path,omitempty"`
	Used        uint64         `json:"tool_calls_used"`
	Evidence    []FileEvidence `json:"evidence"`
}

func ParseFileTask(raw string) (FileTask, error) {
	var task FileTask
	decoder := json.NewDecoder(bytes.NewBufferString(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&task); err != nil {
		return task, err
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return task, fmt.Errorf("trailing task JSON")
	}
	if task.Kind != "ensure_text_files" || len(task.Files) == 0 || len(task.Files) > 3 {
		return task, fmt.Errorf("native file Agent requires one to three text-file goals")
	}
	seen := map[string]bool{}
	for _, goal := range task.Files {
		if !validPath(goal.Path, false) || len(goal.Content) > MaxFileBytes || seen[goal.Path] {
			return task, ErrBoundary
		}
		seen[goal.Path] = true
	}
	return task, nil
}
func reason(err error) string {
	switch {
	case errors.Is(err, ErrBoundary):
		return "boundary_denied"
	case errors.Is(err, ErrBudget):
		return "budget_exhausted"
	case errors.Is(err, ErrStopped), errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return "stopped"
	case errors.Is(err, ErrConflict):
		return "workspace_changed"
	default:
		return "operation_unconfirmed"
	}
}

// RunFileGoals observes the current workspace, changes only unmet goals, and
// measures the actual post-write contents before advancing to the next goal.
// Evidence is generated by the host's file reader, never by a model assertion.
func RunFileGoals(ctx context.Context, tools *Tools, task FileTask) Outcome {
	outcome := Outcome{Status: "submitted", Evidence: []FileEvidence{}}
	for i, goal := range task.Files {
		prefix := fmt.Sprintf("file-goal-%d-", i+1)
		current, err := tools.Call(ctx, Call{ID: prefix + "observe", Action: Read, Path: goal.Path})
		missing := errors.Is(err, fs.ErrNotExist)
		if err != nil && !missing {
			outcome.Status = "blocked"
			outcome.Reason = reason(err)
			outcome.BlockedPath = goal.Path
			break
		}
		expected := contentHash([]byte(goal.Content))
		if missing || current.Hash != expected {
			_, err = tools.Call(ctx, Call{ID: prefix + "change", Action: Write, Path: goal.Path, Content: goal.Content, ExpectedHash: current.Hash})
			if err != nil {
				outcome.Status = "blocked"
				outcome.Reason = reason(err)
				outcome.BlockedPath = goal.Path
				break
			}
			current, err = tools.Call(ctx, Call{ID: prefix + "measure", Action: Read, Path: goal.Path})
			if err != nil {
				outcome.Status = "blocked"
				outcome.Reason = reason(err)
				outcome.BlockedPath = goal.Path
				break
			}
		}
		verified := current.Hash == expected
		outcome.Evidence = append(outcome.Evidence, FileEvidence{Path: goal.Path, ExpectedHash: expected, ObservedHash: current.Hash, Verified: verified, ObservedAt: current.ObservedAt})
		if !verified {
			outcome.Status = "blocked"
			outcome.Reason = "measurement_mismatch"
			outcome.BlockedPath = goal.Path
			break
		}
	}
	outcome.Used = tools.Used()
	return outcome
}
